# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install dependencies and ignore scripts, then build
RUN npm install --ignore-scripts
COPY . .
RUN npm run build

# Expose port if needed (MCP typically uses stdio, so no port exposed)

CMD ["node", "dist/index.js"]
